.TH __GET_INMEMORY_CACHE 1 2025-Jun "" "__get_inmemory_cache"
.SH NAME
__get_inmemory_cache \- __get_inmemory_cache()
.SH SYNOPSIS
\fI__get_inmemory_cache()\fR
.SH FILES
.PP
SMRUCC/R#.declare_function.__get_inmemory_cache at env.R:line 1
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2025
