.TH CHARACTER_COLORSET 1 2023-Apr "" "character_colorSet"
.SH NAME
character_colorSet \- character_colorSet(
    <i>name</i> = albedo)
.SH SYNOPSIS
\fIcharacter_colorSet(
    <i>name</i> = albedo)\fR
.SH OPTIONS
.PP
\fBname\fB \fR\- albedo. 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.character_colorSet at genshin_characters.R:line 9
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
