.TH SCALE_COLOUR_GENSHIN 1 2023-Apr "" "scale_colour_genshin"
.SH NAME
scale_colour_genshin \- scale_colour_genshin(
    <i>name</i> = keys())
.SH SYNOPSIS
\fIscale_colour_genshin(
    <i>name</i> = keys())\fR
.SH OPTIONS
.PP
\fBname\fB \fR\- keys(). 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.scale_colour_genshin at genshin_characters.R:line 5
.PP
.SH COPYRIGHT
Copyright © xieguigang <xie.guigang@gcmodeller.org>, MIT License Licensed 2023
