-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 22:20:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pakchoi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pakchoi` ;

-- -----------------------------------------------------
-- Schema pakchoi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pakchoi` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `pakchoi` ;

-- -----------------------------------------------------
-- Table `user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_roles` (
  `id` INT NOT NULL,
  `role_name` VARCHAR(64) NOT NULL,
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(512) NOT NULL,
  `nickname` VARCHAR(128) NOT NULL,
  `role` INT NOT NULL DEFAULT 0,
  `avatar` TINYTEXT NULL,
  `fullname` VARCHAR(64) NOT NULL,
  `whats_up` VARCHAR(1024) NULL,
  `activities` INT NOT NULL DEFAULT 0,
  `photos` INT NOT NULL DEFAULT 0,
  `posts` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `users` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pageview`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pageview` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pageview` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NOT NULL DEFAULT NOW(),
  `code` INT NOT NULL DEFAULT 200 COMMENT '访问的结果代码\n\n200 正常\n403 被拒绝\n500 服务器错误',
  `page_url` VARCHAR(2048) NOT NULL,
  `user_id` INT NOT NULL,
  `ip` VARCHAR(32) NOT NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `pageview` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `blogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `blogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` INT NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `create_time` DATETIME NOT NULL DEFAULT NOW(),
  `last_modify` DATETIME NOT NULL DEFAULT NOW(),
  `content_resource` MEDIUMTEXT NOT NULL COMMENT '博客文档的路径',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `blogs` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `resources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resources` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `resources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL COMMENT 'file type enum values [for upload folder]',
  `filename` VARCHAR(128) NOT NULL,
  `upload_time` DATETIME NOT NULL,
  `size` INT NOT NULL COMMENT 'size in bytes',
  `description` MEDIUMTEXT NULL,
  `uploader` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用于存储上传的相片，声音，视频等文件';

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `resources` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `messages` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `send_from` INT NOT NULL,
  `message_time` DATETIME NOT NULL,
  `message` LONGTEXT NOT NULL,
  `mentions` INT NOT NULL DEFAULT -1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `messages` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `activity` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL DEFAULT 0,
  `content` MEDIUMTEXT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `activity` (`id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
