-- MySQL Script generated by MySQL Workbench
-- Mon Jan 13 23:32:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema diary
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `diary` ;

-- -----------------------------------------------------
-- Schema diary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diary` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `diary` ;

-- -----------------------------------------------------
-- Table `user_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_roles` (
  `id` INT NOT NULL,
  `role_name` VARCHAR(64) NOT NULL,
  `note` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(512) NOT NULL,
  `nickname` VARCHAR(128) NOT NULL,
  `role` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `users` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `visitors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `visitors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `visitors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NOT NULL DEFAULT NOW(),
  `code` INT NOT NULL DEFAULT 200,
  `visits` VARCHAR(2048) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `visitors` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `blogs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `blogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` INT NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `blogs` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `resources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resources` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `resources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL COMMENT 'file type enum values [for upload folder]',
  `filename` VARCHAR(128) NOT NULL,
  `upload_time` DATETIME NOT NULL,
  `size` INT NOT NULL COMMENT 'size in bytes',
  `description` MEDIUMTEXT NULL,
  `uploader` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `resources` (`id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `chats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chats` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `chats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `send_from` INT NOT NULL,
  `send_time` DATETIME NOT NULL,
  `message` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `chats` (`id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
